name: Deploy functions

on:
  push:
    paths:
      - 'packages/web-next/functions/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: corepack enable
      - name: npm install
        run: cd packages/web-next/functions && npm install
      - name: back to project folder
        run: cd ..
      - name: Deploy
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: packages/web-next
        with:
          args: deploy --only functions
