name: Deploy functions

on:
  push:
    paths:
      - 'packages/web-next/functions/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: corepack enable
      - name: yarn
        run: cd packages/web-next && yarn
      - name: npm install
        run: cd packages/web-next/functions && npm install
      - name: Deploy

        uses: w9jds/firebase-action@master
        env:
          GCP_SA_KEY: ${{ secrets.FUNCTIONS_GCP_SA_KEY }}
          PROJECT_PATH: packages/web-next
        with:
          args: deploy --only functions
